### ISSUE TITLE
[Refactor] Major release 

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/observable#19]
- [x] split of is (already is its own repo) -- mostly used in native tests
- [x] split of storage --- mostly used in adm and sbs
- [x] remove as many getters as possible
- [x] handle remove emitter completely correct (no emit when not necessary)
- [x] streamline event to the absolute maximum, maybe remove it altogether (its confusing)
- [x] replace event /w vigour-stamp
- [x] don't care about things like -- first nested fields etc -- just make it fast -- (api is less important)
- [x] remove all 'nice' extras like property emitters etc, use state if you want this
- [x] don't do if checks in methods do it before (e.g. this._keys || this.keys())
- [x] replace .val with compute
- [x] remove unnecessary properties
- [x] remove value emitter (never used, confusing and slow)
- [x] performance -- increase from 100k/updates/sec to  2m/updates/sec -- at 15 mil /per sec and counting :dancer: 
- [x] context speed up
- [x] references / cleanup and speed up
- [x] ~~docs #21~~~ move to june 
- [x] shorter field names for critical lookups
- [x] replaced all fields starting with _context with _c
- [x] replaced _instances with _i

**Comment by jimdebeer** [comment]
fix the performance!

**Comment by jimdebeer** [comment]
want to be able to do millions of emits/sec 

hot areas
- [ ] remove as many getters as possible
- [ ] handle remove emitter completely correct (no emit when not necessary)
- [ ] streamline event to the absolute maximum, maybe remove it altogether (its confusing)
- [ ] replace event /w vigour-stamp
- [ ] don't care about things like -- first nested fields etc -- just make it fast -- (api is less important)
- [ ] remove all 'nice' extras like property emitters etc, use state if you want this
- [ ] don't do if checks in methods do it before (e.g. this._keys || this.keys())

**Comment by jimdebeer** [comment]
@youzi did I miss anything here?

**Comment by youzi** [comment]
@jimdebeer 
- [x] replacing all getters with methods
- [x] optimising for speed, while maintaining a consistent (perhaps less convenient) api
- [x] object operators
