### ISSUE TITLE
[Emitter] Attach remove unessecary functionalities

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/observable#40]
- [ ] only use attach to attach base/observable remove option to add multiple other arguments

**Comment by jimdebeer** [comment]
rename to bind?

remove array syntax write it like this ?
{ val:  ,   bind:  }

**Comment by jimdebeer** [comment]
current idea is

`on({ val: fn, attach: obs })`

**Comment by jimdebeer** [comment]
need to refactor on and everything for this

**Comment by jimdebeer** [comment]
cant do the fields -- does not work in object notation will stay an array

**Comment by shawninder** [comment]
Will needs super good docs then
