### ISSUE TITLE
Replacements / printf() functionality

### ISSUE THREAD

**Issue by nfrade** [vigour-io/observable#52]
Would be great to have some sort of printf functionality in observables.

For example in data:

``` javascript
{
  subtitle: {
    val: 'This is a text with $something$ inside',
    $replace: {
      '$something$': [ '$', 'some', 'other', 'place' ]
    }
  }
}
```

I can do this with $transform right now but this way it would be more decoupled

**Comment by jimdebeer** [comment]
this can be added as an operator, similar to for example time or type, like the idea - sort of a template - lets check this tmrw but looks good!

**Comment by jimdebeer** [comment]
maybe call it $template or something -- hmm its the result of the template
syntax

`'hello im a string ${hello}'`

```
{
  subtitle: {
    val: 'hello im a string ${hello}',
    $replace: {
      hello: '$root.a.b.c'
    }
  }
}
```

also array notation for references is deprecated in 2.0.0 only the string still works (just to have less options to do the same things)

**Comment by jimdebeer** [comment]
tell me what you think of this syntax -- may be confusing and your syntax is more extendable - but for extendibility $transform is fine I geuss

**Comment by nfrade** [comment]
I like the `"${}"` syntax. And if we already have lodash loaded (don't know if it's the case) them using `_.template()` functionality sounds perfect

**Comment by nfrade** [comment]
And in that case `$template` makes more sense. I guess

**Comment by jimdebeer** [comment]
o ill write something to do the replace don't need lodash for that ;) but lets see tomorrow will only take me around 15 min just the spec how you want it thats where the time is at

**Comment by nfrade** [comment]
Ok great.

**Comment by jimdebeer** [comment]
think its mostly a thing you want in brisky to support multiple subscriptions
