### ISSUE TITLE
once behaviour with instances

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/observable#71]
what do we exactly want for this?

``` javascript
a.once(() => {})
b = new a.Constructor()
```

do we want once to fire for b as well? (not really once anymore)

**Comment by marcusbesjes** [comment]
@jimdebeer have you decided on this?

**Comment by vigourmachines** [comment]
currently I am not doing updates to instances for practically purposes but
may not be a good reason (is expects a real once) @youzi what do you think?

**Comment by youzi** [comment]
I think it should fire (once) for every instance.

If `a` (constructor) depends on this once listener, good chance `b` depends on it as well.

**Comment by jimdebeer** [comment]
ok and then a special handle in is?

**Comment by jimdebeer** [comment]
it is decided then!
